version: '3.9'

services:
  api-services:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8088'
    networks:
      - backend

networks:
  backend:
    driver: bridge